//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WirePeep.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WirePeep.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Defaults&gt;
        ///	&lt;PeerGroup Name=&quot;DNS&quot; FailSeconds=&quot;10&quot; PollSeconds=&quot;5&quot; WaitMilliseconds=&quot;200&quot;&gt;
        ///		&lt;!-- Compare at https://www.dnsperf.com/. --&gt;
        ///		&lt;Location Name=&quot;Google&quot;&gt;
        ///			&lt;Address&gt;8.8.8.8&lt;/Address&gt;
        ///			&lt;Address&gt;8.8.4.4&lt;/Address&gt;
        ///		&lt;/Location&gt;
        ///		&lt;Location Name=&quot;CloudFlare&quot;&gt;
        ///			&lt;Address&gt;1.1.1.1&lt;/Address&gt;
        ///			&lt;Address&gt;1.0.0.1&lt;/Address&gt;
        ///		&lt;/Location&gt;
        ///		&lt;Location Name=&quot;Neustar&quot;&gt;
        ///			&lt;Address&gt;156.154.70.5&lt;/Address&gt;
        ///			&lt;Address&gt;156.154.71.5&lt;/Address&gt;
        ///		&lt;/Location&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultProfileXml {
            get {
                return ResourceManager.GetString("DefaultProfileXml", resourceCulture);
            }
        }
    }
}
